spring:
  application:
    name: wallet-api
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: "jdbc:postgresql://dpg-cu62oh5svqrc738euasg-a.oregon-postgres.render.com:5432/wallet_dv0m"
    username: "wallet_dv0m_user"
    password: "gDHpKceQTcKP1DQw6HjsQMBUyiRMN0SB"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  secret-key: d98c63bf732a3d4cad01e608be321cb40c37bb825de02c9e76edd7aef18553d3
  expiration: 86400000

# Frontend URL
frontend:
  url: ${FRONTEND_URL}